package com.github.cwilper.fcrepo.cloudsync.service.dao;

import com.github.cwilper.fcrepo.cloudsync.api.ObjectInfo;
import com.github.cwilper.fcrepo.cloudsync.api.ObjectStore;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.ArrayList;
import java.util.List;

public class ObjectStoreDao extends AbstractDao {

    private static final String CREATE_DDL =
              "CREATE TABLE ObjectStore (\n"
            + "  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n"
            + "  name VARCHAR(256) NOT NULL,\n"
            + "  type VARCHAR(32) NOT NULL,\n"
            + "  data VARCHAR(1024) NOT NULL,\n"
            + "  CONSTRAINT ObjectStoreUniqueName unique (name))";

    private static final String[] VALID_TYPES = { "fedora", "duracloud" };

    public ObjectStoreDao(JdbcTemplate db) {
        super(db);
    }

    @Override
    public void initDb() {
        db.execute(CREATE_DDL);
    }

    public ObjectStore createObjectStore(ObjectStore objectStore) {
        return objectStore;
    }

    private void validate(ObjectStore o, boolean isNew) {
        /*
        if (isNew || (o.name != null && o.name.trim().length() > 0)) {
            o.name = validateString("name", o.name, 256);
        }
        if (isNew || (o.type != null && o.type.trim().length() > 0)) {
        }
        String type = validateString("type", input.type, VALID_TYPES);
        String data = validateJson("data", input.data, new String[] {"url"});
        ObjectStore output = new ObjectStore();
        output.id = input.id;
        */
    }

    public List<ObjectStore> listObjectStores() {
        List<ObjectStore> list = new ArrayList<ObjectStore>();
        ObjectStore item = new ObjectStore();
        item.setId("1");
        list.add(item);
        return list;
    }

    public ObjectStore getObjectStore(String id) {
        ObjectStore item = new ObjectStore();
        item.setId(id);
        return item;
    }

    public List<ObjectInfo> queryObjectStore(String id, String set, long limit, long offset) {
        List<ObjectInfo> list = new ArrayList<ObjectInfo>();
        ObjectInfo item = new ObjectInfo();
        item.setPid("test:object1");
        list.add(item);
        return list;
    }

    public ObjectStore updateObjectStore(String id, ObjectStore objectStore) {
        return objectStore;
    }

    public void deleteObjectStore(String id) {
    }

}